### PR TITLE
register freeze_time mark with pytest

### PR DESCRIPTION
**Pull request by dimaqq**
For https://github.com/ktosiek/pytest-freezegun/issues/13

### CODE REVIEW

**Review by alysivji — APPROVED** [review]
LGTM. Straight out of the [pytest docs](https://docs.pytest.org/en/latest/writing_plugins.html#registering-markers)

**Comment by dimaqq** [comment]
Help needed to pacify continuous testing.

**Comment by alysivji** [comment]
Looks like the other PRs are failing with the same build... I don't have a Windows machine to test it out, but I did notice that the [warning still does show up in the builds](https://ci.appveyor.com/project/ktosiek/pytest-freezegun/builds/24997508/job/1rxvfrrtk51o2ubs):

```
PytestUnknownMarkWarning: Unknown pytest.mark.freeze_time - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
```

Taking a look at the docs again... you have the function in a class, [in the docs](https://docs.pytest.org/en/latest/writing_plugins.html#registering-custom-markers), the function is in the module. Maybe that's the problem?

**Comment by ktosiek** [comment]
This was fixed by other PRs (#17 and #20). I'm closing this one.

**Pull request closed without merging**
